Repository Ashlar/binance-api-node, pull requests merged in 2018-03, with the labels that each got.

#57 Fix typo
  src/http.js
Labels: docs

#55 More typings
  index.d.ts
Labels: types

#56 Added Candlestick chart intervals
  index.d.ts
Labels: types

#49 Reconnecting WebSocket
  package.json
  src/open-websocket.js
  src/websocket.js
  test/index.js
  test/websocket-reconnect.js
  yarn.lock
Labels: enhancement

#60 Expose error codes
  src/http.js
  test/authenticated.js
Labels: enhancement

#66 Expose error code in definition file
  index.d.ts
Labels: types

#73 Adding type definitions to the dailyStats method
  README.md
  index.d.ts
Labels: types

#74 Typed candles
  index.d.ts
Labels: types

#77 Support string arrays for "depth"
  index.d.ts
Labels: types
