Repository Ashlar/binance-api-node, pull requests merged in 2018-02, with the labels that each got.

#45 Use standard name for type definitions
  index.d.ts
  package.json
Labels: enhancement

#48 Fix close handle for `client.ws.depth`
  src/websocket.js
Labels: bug

#52 index.d.ts - necessary changes that were missed in release 0.5.7
  index.d.ts
Labels: docs, enhancement

#53 Added typing for book() and exchangeInfo() HTTP methods
  index.d.ts
Labels: types
