Repository Ashlar/binance-api-node, pull requests merged in 2018-04, with the labels that each got.

#79 Add "cancelOrder" response
  README.md
Labels: docs

#78 Add "openOrders" response
  README.md
Labels: docs

#82 Support "options" for WebSocket reconnect
  src/websocket.js
Labels: enhancement

#85 Add "useServerTime" for authenticated endpoints
  index.d.ts
Labels: types

#84 fix issue header Sec-WebSocket-Protocol was null
  src/open-websocket.js
Labels: bug

#91 Add types for "aggTrades"
  index.d.ts
Labels: types
