Repository Ashlar/binance-api-node, pull requests merged in 2019-03, with the labels that each got.

#162 Add support for the optional field 'timeOffset' to be used in private calls
  README.md
  index.d.ts
  src/http.js
Labels: enhancement

#163 make symbol optional
  index.d.ts
Labels: types

#167 Update README.md
  README.md
Labels: docs

#166 add allOrders type definitions.
  index.d.ts
Labels: types
