Repository Ashlar/binance-api-node, pull requests merged in 2019-10, with the labels that each got.

#197 fix: Export missing enums
  src/index.js
Labels: types

#198 missing field totalQuoteTradeQuantity
  index.d.ts
Labels: types

#201 provide Binance margin websocket stream and basic margin trading endpoints support
  README.md
  src/http-client.js
  src/websocket.js
Labels: enhancement

#199 chore(typings): Mark depositTip as optional
  index.d.ts
Labels: types

#203 docs: Fix typos in output payloads
  README.md
Labels: docs

#205 move all path urls inside calls itself and prepare futures endpoint; also usage of unmanaged public / private calls
  src/http-client.js
Labels: enhancement
