Repository Ashlar/binance-api-node, pull requests merged in 2020-06, with the labels that each got.

#260 Support call to cancel all orders on a symbol
  README.md
  index.d.ts
  src/http-client.js
  test/auth.js
Labels: enhancement

#261 Fix table in readme for cancelOpenOrders
  README.md
Labels: docs

#262 feat(websocket): Map balance update user event
  index.d.ts
  src/websocket.js
Labels: enhancement

#263 feat(websocket): Extend execution report types
  index.d.ts
  src/websocket.js
Labels: enhancement, types
