Repository Ashlar/binance-api-node, pull requests merged in 2021-05, with the labels that each got.

#407 Support dust transfer
  README.md
  src/http-client.js
Labels: enhancement

#412 Adds support for asset info
  README.md
  src/http-client.js
Labels: enhancement

#417 Add Notional and Leverage Brackets
  README.md
  index.d.ts
  src/http-client.js
Labels: enhancement, types

#421 ✨ feat: bnb burn
  README.md
  index.d.ts
  src/http-client.js
Labels: docs, enhancement, types
