Repository Ashlar/binance-api-node, pull requests merged in 2021-06, with the labels that each got.

#433 Fixes missing `Futures Public REST Endpoints` h3 in README
  README.md
Labels: docs

#435 Add missing typings for the OCO order methods
  index.d.ts
Labels: types

#443 Add openOrders and allOrders Typescript properties
  index.d.ts
Labels: types

#445 Use node-fetch v2.6.1
  package.json
  yarn.lock
Labels: enhancement

#446 Adding WebSocket futuresTicker to type definitions
  index.d.ts
Labels: types

#448 Typings for cross margin account info
  README.md
  index.d.ts
Labels: docs, types

#451 Typo in typings
  README.md
  index.d.ts
Labels: docs, types

#455 Fix for futuresCancelAllOpenOrders and futuresBatchOrders
  src/http-client.js
Labels: enhancement

#462 Update index.d.ts
  index.d.ts
Labels: types

#465 Order type update
  index.d.ts
Labels: types
