Repository Ashlar/binance-api-node, pull requests merged in 2021-02, with the labels that each got.

#330 fix typo
  src/http-client.js
Labels: bug

#334 Specify order type & order side
  index.d.ts
Labels: types

#341 add support for futures liquidation streams
  README.md
  index.d.ts
  src/websocket.js
  test/index.js
Labels: enhancement

#345 add AccountUpdate type and fix mapping
  index.d.ts
  src/websocket.js
Labels: enhancement

#349 Added isomorphic-ws which supports both node and browser environments.
  package.json
  src/open-websocket.js
Labels: enhancement

#351 Update Speed for Diff. Depth Stream & Partial Book Depth Streams
  README.md
  src/websocket.js
  test/index.js
Labels: enhancement

#352 Add the methods getOrderOco & cancelOrderOco
  README.md
  src/http-client.js
Labels: enhancement

#354 Add various missing types
  index.d.ts
Labels: types
