Repository Ashlar/binance-api-node, pull requests merged in 2021-04, with the labels that each got.

#372 add websocket endpoint mini ticker
  README.md
  src/websocket.js
  test/index.js
Labels: enhancement

#384 Change outdated urls WAPI to SAPI
  README.md
  src/http-client.js
Labels: enhancement

#388 Update Stop orders and added `TRAILING_STOP_MARKET`
  README.md
  index.d.ts
  src/http-client.js
Labels: docs

#387 feat: add custom sub stream
  README.md
  index.d.ts
  src/websocket.js
Labels: enhancement

#392 Update tradeFee typings
  index.d.ts
Labels: types
